name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t moontris/devopshow .
      - name: Push Docker image
        run: docker image push moontris/devopshow
      - name: Run WebApp
        run: docker run -dp 3000:3000 moontris/devopshow
